import datetime

from csc.models import db, User
from csc.security import hash_password

db.schools.drop()
db.schools.insert_many([
    {'_id': 1,
     'name': 'Avila University',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 2,
     'name': 'Baptist Bible College and Graduate School',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 3,
     'name': 'Brown Mackie College St Louis',
     'city': 'Fenton',
     'state': 'Missouri'},
    {'_id': 4,
     'name': 'Bryan University Springfield',
     'city': 'Springfield',
     'state': 'Missouri',
     'image': 'BryanUniversity'},
    {'_id': 5,
     'name': 'Calvary Bible College and Theological Seminary',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 6,
     'name': 'Central Bible College',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 7,
     'name': 'Central Christian College of the Bible',
     'city': 'Moberly',
     'state': 'Missouri'},
    {'_id': 8,
     'name': 'Central Methodist University College of Liberal Arts & Sciences',
     'city': 'Fayette',
     'state': 'Missouri'},
    {'_id': 9,
     'name': 'Chamberlain College of Nursing Missouri',
     'city': 'St. Louis',
     'state': 'Missouri'},
    {'_id': 10,
     'name': 'College of the Ozarks',
     'city': 'Point Lookout',
     'state': 'Missouri'},
    {'_id': 11,
     'name': 'Colorado Technical University Kansas City',
     'city': 'North Kansas City',
     'state': 'Missouri'},
    {'_id': 12,
     'name': 'Columbia College',
     'city': 'Columbia',
     'state': 'Missouri'},
    {'_id': 13,
     'name': 'Conception Seminary College',
     'city': 'Conception',
     'state': 'Missouri'},
    {'_id': 14,
     'name': 'Cottey College',
     'city': 'Nevada',
     'state': 'Missouri'},
    {'_id': 15,
     'name': 'Cox College',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 16,
     'name': 'Crowder College',
     'city': 'Neosho',
     'state': 'Missouri'},
    {'_id': 17,
     'name': 'Culver Stockton College',
     'city': 'Canton',
     'state': 'Missouri'},
    {'_id': 18,
     'name': 'DeVry University Missouri',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 19,
     'name': 'Drury University',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 20,
     'name': 'East Central College',
     'city': 'Union',
     'state': 'Missouri'},
    {'_id': 21,
     'name': 'Evangel University',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 22,
     'name': 'Everest College Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 23,
     'name': 'Fontbonne University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 24,
     'name': 'Grantham University',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 25,
     'name': 'Hannibal LaGrange University',
     'city': 'Hannibal',
     'state': 'Missouri'},
    {'_id': 26,
     'name': 'Harris Stowe State University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 27,
     'name': 'Hickey College',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 28,
     'name': 'ITT Technical Institute Arnold',
     'city': 'Arnold',
     'state': 'Missouri'},
    {'_id': 29,
     'name': 'ITT Technical Institute Earth City',
     'city': 'Earth City',
     'state': 'Missouri'},
    {'_id': 30,
     'name': 'ITT Technical Institute Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 31,
     'name': 'ITT Technical Institute Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 32,
     'name': 'Jefferson College',
     'city': 'Hillsboro',
     'state': 'Missouri'},
    {'_id': 33,
     'name': 'Kansas City Art Institute',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 34,
     'name': 'Kenrick Glennon Seminary',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 35,
     'name': 'L\'Ecole Culinaire',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 36,
     'name': 'Lincoln University',
     'city': 'Jefferson City',
     'state': 'Missouri'},
    {'_id': 37,
     'name': 'Lindenwood University',
     'city': 'Saint Charles',
     'state': 'Missouri'},
    {'_id': 38,
     'name': 'Linn State Technical College',
     'city': 'Linn',
     'state': 'Missouri'},
    {'_id': 39,
     'name': 'Maryville University of Saint Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 40,
     'name': 'Messenger College',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 41,
     'name': 'Metro Business College Arnold',
     'city': 'Arnold',
     'state': 'Missouri'},
    {'_id': 42,
     'name': 'Metro Business College Cape Girardeau',
     'city': 'Cape Girardeau',
     'state': 'Missouri'},
    {'_id': 43,
     'name': 'Metro Business College Jefferson City',
     'city': 'Jefferson City',
     'state': 'Missouri'},
    {'_id': 44,
     'name': 'Metro Business College Rolla',
     'city': 'Rolla',
     'state': 'Missouri'},
    {'_id': 45,
     'name': 'Metropolitan Community College Blue River',
     'city': 'Independence',
     'state': 'Missouri'},
    {'_id': 46,
     'name': 'Metropolitan Community College Business & Technology',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 47,
     'name': 'Metropolitan Community College Longview',
     'city': 'Lees Summit',
     'state': 'Missouri'},
    {'_id': 48,
     'name': 'Metropolitan Community College Maple Woods',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 49,
     'name': 'Metropolitan Community College Penn Valley',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 50,
     'name': 'Midwestern Baptist Theological Seminary',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 51,
     'name': 'Mineral Area College',
     'city': 'Park Hills',
     'state': 'Missouri'},
    {'_id': 52,
     'name': 'Missouri Baptist University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 53,
     'name': 'Missouri College',
     'city': 'Brentwood',
     'state': 'Missouri'},
    {'_id': 54,
     'name': 'Missouri Southern State University',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 55,
     'name': 'Missouri State University Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 56,
     'name': 'Missouri State University West Plains',
     'city': 'West Plains',
     'state': 'Missouri'},
    {'_id': 57,
     'name': 'Missouri Tech',
     'city': 'Saint Charles',
     'state': 'Missouri'},
    {'_id': 58,
     'name': 'Missouri University of Science and Technology',
     'city': 'Rolla',
     'state': 'Missouri'},
    {'_id': 59,
     'name': 'Missouri Valley College',
     'city': 'Marshall',
     'state': 'Missouri'},
    {'_id': 60,
     'name': 'Missouri Western State University',
     'city': 'Saint Joseph',
     'state': 'Missouri'},
    {'_id': 61,
     'name': 'Moberly Area Community College',
     'city': 'Moberly',
     'state': 'Missouri'},
    {'_id': 62,
     'name': 'National American University Independence',
     'city': 'Independence',
     'state': 'Missouri'},
    {'_id': 63,
     'name': 'National American University Lee\'s Summit',
     'city': 'Lee Summit',
     'state': 'Missouri'},
    {'_id': 64,
     'name': 'National American University Zona Rosa',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 65,
     'name': 'North Central Missouri College',
     'city': 'Trenton',
     'state': 'Missouri'},
    {'_id': 66,
     'name': 'Northwest Missouri State University',
     'city': 'Maryville',
     'state': 'Missouri'},
    {'_id': 67,
     'name': 'Ozark Christian College',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 68,
     'name': 'Ozarks Technical Community College',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 69,
     'name': 'Park University',
     'city': 'Parkville',
     'state': 'Missouri'},
    {'_id': 70,
     'name': 'Pinnacle Career Institute North Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 71,
     'name': 'Pinnacle Career Institute South Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 72,
     'name': 'Ranken Technical College',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 73,
     'name': 'Research College of Nursing',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 74,
     'name': 'Rockhurst University',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 75,
     'name': 'Saint Louis Christian College',
     'city': 'Florissant',
     'state': 'Missouri'},
    {'_id': 76,
     'name': 'Saint Louis Community College',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 77,
     'name': 'Saint Louis University Main Campus',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 78,
     'name': 'Sanford Brown College Fenton',
     'city': 'Fenton',
     'state': 'Missouri'},
    {'_id': 79,
     'name': 'Sanford Brown College Hazelwood',
     'city': 'Hazelwood',
     'state': 'Missouri'},
    {'_id': 80,
     'name': 'Sanford Brown College St Peters',
     'city': 'Saint Peters',
     'state': 'Missouri'},
    {'_id': 81,
     'name': 'Southeast Missouri Hospital College of Nursing and Health Sciences',
     'city': 'Cape Girardeau',
     'state': 'Missouri'},
    {'_id': 82,
     'name': 'Southeast Missouri State University',
     'city': 'Cape Girardeau',
     'state': 'Missouri'},
    {'_id': 83,
     'name': 'Southwest Baptist University',
     'city': 'Bolivar',
     'state': 'Missouri'},
    {'_id': 84,
     'name': 'St Charles Community College',
     'city': 'Cottleville',
     'state': 'Missouri'},
    {'_id': 85,
     'name': 'St Louis College of Health Careers Fenton',
     'city': 'Fenton',
     'state': 'Missouri'},
    {'_id': 86,
     'name': 'St Louis College of Health Careers St Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 87,
     'name': 'St Louis College of Pharmacy',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 88,
     'name': 'State Fair Community College',
     'city': 'Sedalia',
     'state': 'Missouri'},
    {'_id': 89,
     'name': 'Stephens College',
     'city': 'Columbia',
     'state': 'Missouri'},
    {'_id': 90,
     'name': 'Stevens Institute of Business & Arts',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 91,
     'name': 'Texas County Technical College',
     'city': 'Houston',
     'state': 'Missouri'},
    {'_id': 92,
     'name': 'Three Rivers Community College',
     'city': 'Poplar Bluff',
     'state': 'Missouri'},
    {'_id': 93,
     'name': 'Truman State University',
     'city': 'Kirksville',
     'state': 'Missouri'},
    {'_id': 94,
     'name': 'University of Central Missouri',
     'city': 'Warrensburg',
     'state': 'Missouri'},
    {'_id': 95,
     'name': 'University of Missouri Columbia',
     'city': 'Columbia',
     'state': 'Missouri'},
    {'_id': 96,
     'name': 'University of Missouri Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 97,
     'name': 'University of Missouri St Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 98,
     'name': 'University of Phoenix Kansas City Campus',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 99,
     'name': 'University of Phoenix Springfield Campus',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 100,
     'name': 'University of Phoenix St Louis Campus',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 101,
     'name': 'Vatterott College Berkeley',
     'city': 'Berkeley',
     'state': 'Missouri'},
    {'_id': 102,
     'name': 'Vatterott College Joplin',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 103,
     'name': 'Vatterott College Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 104,
     'name': 'Vatterott College Saint Joseph',
     'city': 'Saint Joseph',
     'state': 'Missouri'},
    {'_id': 105,
     'name': 'Vatterott College Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 106,
     'name': 'Vatterott College St Charles',
     'city': 'St Charles',
     'state': 'Missouri'},
    {'_id': 107,
     'name': 'Vatterott College Sunset Hills',
     'city': 'Sunset Hills',
     'state': 'Missouri'},
    {'_id': 108,
     'name': 'Washington University in St Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 109,
     'name': 'Webster University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 110,
     'name': 'Wentworth Military Academy & Junior College',
     'city': 'Lexington',
     'state': 'Missouri'},
    {'_id': 111,
     'name': 'Westminster College',
     'city': 'Fulton',
     'state': 'Missouri'},
    {'_id': 112,
     'name': 'William Jewell College',
     'city': 'Liberty',
     'state': 'Missouri'},
    {'_id': 113,
     'name': 'William Woods University',
     'city': 'Fulton',
     'state': 'Missouri'},
])

db.users.drop()
db.users.insert_many([
    {'_id': 1,
     'name': 'Stefano Menci',
     'admin': 1,
     'email': 'stefano.menci@gmail.com',
     'password': hash_password('stefano'),
     'city': 'Olivette',
     'state': 'Missouri',
     'club_ids': [1, 23, 3],
     'competition_ids': [1, 2],
     'school_ids': [4, 12]},
    {'_id': 2,
     'name': 'Brandon Torres',
     'admin': 1,
     'email': 'brandon.torres@gmail.com',
     'password': hash_password('brandon'),
     'city': 'University City',
     'state': 'Missouri',
     'club_ids': [1, 32, 3],
     'competition_ids': [1, 2],
     'school_ids': [6, 10]},
    {'_id': 3,
     'name': 'Vance Lemoine',
     'email': 'vance.lemoine@gmail.com',
     'password': hash_password('vance'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [13, 2, 3],
     'competition_ids': [1],
     'school_ids': [64]},
    {'_id': 4,
     'name': 'Valencia Tripodi',
     'email': 'valencia.tripodi@gmail.com',
     'password': hash_password('valencia'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': [31, 2, 3],
     'competition_ids': [1],
     'school_ids': [110]},
    {'_id': 5,
     'name': 'Estelle Oram',
     'email': 'estelle.oram@gmail.com',
     'password': hash_password('estelle'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': [1, 2, 32],
     'competition_ids': [1],
     'school_ids': [35]},
    {'_id': 6,
     'name': 'Cornelius Bomberger',
     'email': 'cornelius.bomberger@gmail.com',
     'password': hash_password('cornelius'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': [1, 2, 23],
     'competition_ids': [2],
     'school_ids': [11]},
    {'_id': 7,
     'name': 'Karyl Horvat',
     'email': 'karyl.horvat@gmail.com',
     'password': hash_password('karyl'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': [1, 22, 3],
     'competition_ids': [2],
     'school_ids': [96]},
    {'_id': 8,
     'name': 'Delfina Wescott',
     'email': 'delfina.wescott@gmail.com',
     'password': hash_password('delfina'),
     'major': 'Engineering',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': [12, 2, 3],
     'school_ids': [12]},
    {'_id': 9,
     'name': 'Albina Hudak',
     'email': 'albina.hudak@gmail.com',
     'password': hash_password('albina'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': [21, 2, 3],
     'school_ids': [101]},
    {'_id': 10,
     'name': 'Alicia Sayles',
     'email': 'alicia.sayles@gmail.com',
     'password': hash_password('alicia'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': [1, 2, 31],
     'school_ids': [49]},
    {'_id': 11,
     'name': 'Sade Berney',
     'email': 'sade.berney@gmail.com',
     'password': hash_password('sade'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': [1, 2, 13],
     'school_ids': [63]},
    {'_id': 12,
     'name': 'Royal Perales',
     'email': 'royal.perales@gmail.com',
     'password': hash_password('royal'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': [1, 21, 3],
     'school_ids': [103]},
    {'_id': 13,
     'name': 'Moshe Waage',
     'email': 'moshe.waage@gmail.com',
     'password': hash_password('moshe'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': [1, 12, 3],
     'school_ids': [24]},
    {'_id': 14,
     'name': 'Devon Mcgurk',
     'email': 'devon.mcgurk@gmail.com',
     'password': hash_password('devon'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': [11, 2, 3],
     'school_ids': [42, 6]},
    {'_id': 15,
     'name': 'Kaila Blow',
     'email': 'kaila.blow@gmail.com',
     'password': hash_password('kaila'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': [1, 26, 3],
     'school_ids': [3]},
    {'_id': 16,
     'name': 'Kermit Valladares',
     'email': 'kermit.valladares@gmail.com',
     'password': hash_password('kermit'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': [1, 62, 3],
     'school_ids': [81]},
    {'_id': 17,
     'name': 'Tristan Crigler',
     'email': 'tristan.crigler@gmail.com',
     'password': hash_password('tristan'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'California',
     'club_ids': [1, 2, 36],
     'school_ids': [19]},
    {'_id': 18,
     'name': 'Del Innis',
     'email': 'del.innis@gmail.com',
     'password': hash_password('del'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [1, 2, 63],
     'school_ids': [13]},
    {'_id': 19,
     'name': 'Amy Astin',
     'email': 'amy.astin@gmail.com',
     'password': hash_password('amy'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': [1, 6, 3],
     'school_ids': [76]},
    {'_id': 20,
     'name': 'Elois Nevarez',
     'email': 'elois.nevarez@gmail.com',
     'password': hash_password('elois'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [61, 2, 3],
     'school_ids': [41]},
    {'_id': 21,
     'name': 'Kit Romain',
     'email': 'kit.romain@gmail.com',
     'password': hash_password('kit'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': [16, 2, 3],
     'school_ids': [77]},
    {'_id': 22,
     'name': 'Palma Boldt',
     'email': 'palma.boldt@gmail.com',
     'password': hash_password('palma'),
     'major': 'Engineering',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': [1, 2, 35],
     'school_ids': [17]},
    {'_id': 23,
     'name': 'Lauralee Shewmake',
     'email': 'lauralee.shewmake@gmail.com',
     'password': hash_password('lauralee'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': [1, 2, 53],
     'school_ids': [11]},
    {'_id': 24,
     'name': 'Zaida Lisle',
     'email': 'zaida.lisle@gmail.com',
     'password': hash_password('zaida'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [1, 25, 3],
     'school_ids': [77]},
    {'_id': 25,
     'name': 'Kerrie Lease',
     'email': 'kerrie.lease@gmail.com',
     'password': hash_password('kerrie'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [1, 52, 3],
     'school_ids': [30]},
    {'_id': 26,
     'name': 'Vito Striplin',
     'email': 'vito.striplin@gmail.com',
     'password': hash_password('vito'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': [1, 5, 3],
     'school_ids': [37]},
    {'_id': 27,
     'name': 'Xuan Michelson',
     'email': 'xuan.michelson@gmail.com',
     'password': hash_password('xuan'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': [15, 2, 3],
     'school_ids': [9]},
    {'_id': 28,
     'name': 'Bettyann Julien',
     'email': 'bettyann.julien@gmail.com',
     'password': hash_password('bettyann'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': [51, 2, 3],
     'school_ids': [106]},
    {'_id': 29,
     'name': 'Niki Beecher',
     'email': 'niki.beecher@gmail.com',
     'password': hash_password('niki'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'California',
     'club_ids': [4, 2, 3],
     'school_ids': [29]},
    {'_id': 30,
     'name': 'Saturnina Gandhi',
     'email': 'saturnina.gandhi@gmail.com',
     'password': hash_password('saturnina'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': [1, 2, 34],
     'school_ids': [88]},
    {'_id': 31,
     'name': 'Hubert Stott',
     'email': 'hubert.stott@gmail.com',
     'password': hash_password('hubert'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'California',
     'club_ids': [1, 2, 43],
     'school_ids': [71]},
    {'_id': 32,
     'name': 'Odis Pattison',
     'email': 'odis.pattison@gmail.com',
     'password': hash_password('odis'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': [1, 24, 3],
     'school_ids': [69]},
    {'_id': 33,
     'name': 'Carmelia Brock',
     'email': 'carmelia.brock@gmail.com',
     'password': hash_password('carmelia'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': [1, 4, 3],
     'school_ids': [8]},
    {'_id': 34,
     'name': 'Lacey Corman',
     'email': 'lacey.corman@gmail.com',
     'password': hash_password('lacey'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': [1, 42, 3],
     'school_ids': [106]},
    {'_id': 35,
     'name': 'Denyse Peavler',
     'email': 'denyse.peavler@gmail.com',
     'password': hash_password('denyse'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': [14, 2, 3],
     'school_ids': [56]},
    {'_id': 36,
     'name': 'Regine Rivenburg',
     'email': 'regine.rivenburg@gmail.com',
     'password': hash_password('regine'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': [41, 2, 3],
     'school_ids': [48]},
    {'_id': 37,
     'name': 'Arleen Samons',
     'email': 'arleen.samons@gmail.com',
     'password': hash_password('arleen'),
     'major': 'Engineering',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': [11, 2, 3],
     'school_ids': [101]},
    {'_id': 38,
     'name': 'Mindy Stearman',
     'email': 'mindy.stearman@gmail.com',
     'password': hash_password('mindy'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': [1, 2, 33],
     'school_ids': [30]},
    {'_id': 39,
     'name': 'Henrietta Wolken',
     'email': 'henrietta.wolken@gmail.com',
     'password': hash_password('henrietta'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': [1, 32, 3],
     'school_ids': [97]},
    {'_id': 40,
     'name': 'Jenae Hamm',
     'email': 'jenae.hamm@gmail.com',
     'password': hash_password('jenae'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': [1, 23, 3],
     'school_ids': [77]},
    {'_id': 41,
     'name': 'Pete Pendergraft',
     'email': 'pete.pendergraft@gmail.com',
     'password': hash_password('pete'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': [13, 2, 3],
     'school_ids': [42]},
    {'_id': 42,
     'name': 'Tad Anderton',
     'email': 'tad.anderton@gmail.com',
     'password': hash_password('tad'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [31, 2, 3],
     'school_ids': [48]},
    {'_id': 43,
     'name': 'Vince Sunderman',
     'email': 'vince.sunderman@gmail.com',
     'password': hash_password('vince'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': [1, 2, 32],
     'school_ids': [41]},
    {'_id': 44,
     'name': 'Virgie Hipple',
     'email': 'virgie.hipple@gmail.com',
     'password': hash_password('virgie'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': [1, 2, 23],
     'school_ids': [97]},
    {'_id': 45,
     'name': 'Ashley Gitlin',
     'email': 'ashley.gitlin@gmail.com',
     'password': hash_password('ashley'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': [1, 22, 3],
     'school_ids': [113]},
    {'_id': 46,
     'name': 'Julia Denner',
     'email': 'julia.denner@gmail.com',
     'password': hash_password('julia'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [12, 2, 3],
     'school_ids': [59]},
    {'_id': 47,
     'name': 'Elana Cuffee',
     'email': 'elana.cuffee@gmail.com',
     'password': hash_password('elana'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': [1, 2, 23],
     'school_ids': [81]},
    {'_id': 48,
     'name': 'Rozanne Garden',
     'email': 'rozanne.garden@gmail.com',
     'password': hash_password('rozanne'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': [1, 22, 3],
     'school_ids': [45]},
    {'_id': 49,
     'name': 'Salley Quiroz',
     'email': 'salley.quiroz@gmail.com',
     'password': hash_password('salley'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': [21, 2, 3],
     'school_ids': [84]},
    {'_id': 50,
     'name': 'Ozell Costas',
     'email': 'ozell.costas@gmail.com',
     'password': hash_password('ozell'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': [11, 2, 3],
     'school_ids': [3]},
    {'_id': 51,
     'name': 'Vivienne Hardee',
     'email': 'vivienne.hardee@gmail.com',
     'password': hash_password('vivienne'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': [1, 2, 13],
     'school_ids': [68]},
    {'_id': 52,
     'name': 'Shawnee Driskill',
     'email': 'shawnee.driskill@gmail.com',
     'password': hash_password('shawnee'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': [1, 12, 3],
     'school_ids': [72]}
])

db.clubs.drop()
db.clubs.insert_many([
    {'_id': 1,
     'name': 'Alpha Epsilon-Honors Society',
     'school_id': 7,
     'officers': [
         {'president_id': 2,
          'vicepresident_id': 3,
          'treasurer_id': 4,
          'secretary_id': 5}
     ]},
    {'_id': 2,
     'name': 'Alpha Omega Epsilon Sorority',
     'school_id': 29},
    {'_id': 3,
     'name': 'Alpha Pi Mu - Honors Society',
     'school_id': 23,
     'officers': [
         {'president_id': 1,
          'vicepresident_id': 2,
          'treasurer_id': 3,
          'secretary_id': 6}
     ]},
    {'_id': 4,
     'name': 'American Institute of Aeronautics & Astronautics (AIAA)',
     'school_id': 12},
    {'_id': 5,
     'name': 'American Institute of Chemical Engineers',
     'school_id': 47},
    {'_id': 6,
     'name': 'American Society of Civil Engineers (ASCE)',
     'school_id': 4},
    {'_id': 7,
     'name': 'American Society of Mechanical Engineers',
     'school_id': 35},
    {'_id': 8,
     'name': 'ASME Student Professional Development Conference',
     'school_id': 49,
     'image': 'ASME'},
    {'_id': 9,
     'name': 'Association for Computing Machinery',
     'school_id': 75,
     'officers': [
         {'president_id': 12,
          'vicepresident_id': 13,
          'treasurer_id': 14,
          'secretary_id': 15}
     ]},
    {'_id': 10,
     'name': 'Bioengineering',
     'school_id': 57},
    {'_id': 11,
     'name': 'Biomedical Competitive Advancement Team (BioCATs)',
     'school_id': 34},
    {'_id': 12,
     'name': 'Biomedical Engineering Society',
     'school_id': 109},
    {'_id': 13,
     'name': 'Chemical',
     'school_id': 22},
    {'_id': 14,
     'name': 'Chi Epsilon - Honors Society',
     'school_id': 93},
    {'_id': 15,
     'name': 'Civil & Environmental',
     'school_id': 17},
    {'_id': 16,
     'name': 'Computer Science',
     'school_id': 89},
    {'_id': 17,
     'name': 'Computer Science Graduate Student Council',
     'school_id': 71},
    {'_id': 18,
     'name': 'Concrete Bowling Team',
     'school_id': 30},
    {'_id': 19,
     'name': 'Concrete Canoe Team',
     'school_id': 27},
    {'_id': 20,
     'name': 'Contact Faculty Advisers',
     'school_id': 19},
    {'_id': 21,
     'name': 'ECE Graduate Student Association',
     'school_id': 36},
    {'_id': 22,
     'name': 'Electrical & Computer',
     'school_id': 43},
    {'_id': 23,
     'name': 'Engineer’s Club / St. Pat’s Board',
     'school_id': 5},
    {'_id': 24,
     'name': 'Engineering Ambassadors',
     'school_id': 104},
    {'_id': 25,
     'name': 'Engineering Student Council',
     'school_id': 22},
    {'_id': 26,
     'name': 'Engineering World Health',
     'school_id': 5},
    {'_id': 27,
     'name': 'Engineers Without Borders',
     'school_id': 4},
    {'_id': 28,
     'name': 'Eta Kappa Nu - Honors Society',
     'school_id': 99},
    {'_id': 29,
     'name': 'E-Week (Engineers’ Week)',
     'school_id': 45},
    {'_id': 30,
     'name': 'Formula Car Racing Team (FSAE)',
     'school_id': 27},
    {'_id': 31,
     'name': 'Graduates’ Club of Biological Engineering (GCBE)',
     'school_id': 44},
    {'_id': 32,
     'name': 'IEEE CIS Society',
     'school_id': 56},
    {'_id': 33,
     'name': 'Industrial & Manufacturing Systems',
     'school_id': 75},
    {'_id': 34,
     'name': 'Institute of Biological Engineering',
     'school_id': 15},
    {'_id': 35,
     'name': 'Institute of Electrical and Electronics Engineering (IEEE)',
     'school_id': 91},
    {'_id': 36,
     'name': 'Institute of Industrial Engineers',
     'school_id': 46},
    {'_id': 37,
     'name': 'Mechanical & Aerospace',
     'school_id': 61},
    {'_id': 38,
     'name': 'Mechanical Contractors Association of America',
     'school_id': 112},
    {'_id': 39,
     'name': 'Mizzou 3D Printing Club',
     'school_id': 111},
    {'_id': 40,
     'name': 'Mizzou ASHRAE',
     'school_id': 51},
    {'_id': 41,
     'name': 'Mizzou Baja Racing (BSAE)',
     'school_id': 81},
    {'_id': 42,
     'name': 'Mizzou Eco-Racing',
     'school_id': 94},
    {'_id': 43,
     'name': 'Mizzou Electric Car Club',
     'school_id': 97},
    {'_id': 44,
     'name': 'Mizzou Student Chapter',
     'school_id': 50},
    {'_id': 45,
     'name': 'Mizzou Unmanned Systems Team (MUST)',
     'school_id': 26},
    {'_id': 46,
     'name': 'Mizzou Women Mentoring Women',
     'school_id': 111},
    {'_id': 47,
     'name': 'National Language Processing Journal Club',
     'school_id': 83},
    {'_id': 48,
     'name': 'National Society of Black Engineers',
     'school_id': 111},
    {'_id': 49,
     'name': 'Omega Chi Epsilon - Honors Society',
     'school_id': 81},
    {'_id': 50,
     'name': 'Pi Tau Sigma - Honors Society',
     'school_id': 49},
    {'_id': 51,
     'name': 'Sigma Alpha Sorority',
     'school_id': 13},
    {'_id': 52,
     'name': 'Sigma Phi Delta',
     'school_id': 62},
    {'_id': 53,
     'name': 'Society of Hispanic Professional Engineers',
     'school_id': 6},
    {'_id': 54,
     'name': 'Society of Manufacturing Engineers',
     'school_id': 71},
    {'_id': 55,
     'name': 'Society of Manufacturing Engineers',
     'school_id': 53},
    {'_id': 56,
     'name': 'Society of Women Engineers',
     'school_id': 32},
    {'_id': 57,
     'name': 'Steel Bridge Team',
     'school_id': 62},
    {'_id': 58,
     'name': 'Students for the Exploration and Development of Space (SEDS)',
     'school_id': 83, },
    {'_id': 59,
     'name': 'Tau Beta Pi - Engineering Honors Society',
     'school_id': 26, },
    {'_id': 60,
     'name': 'Timber Bridge Team',
     'school_id': 103, },
    {'_id': 61,
     'name': 'Torq’N Tigers Tractor Pulling TeamGeneral Interest',
     'school_id': 92, },
    {'_id': 62,
     'name': 'Upsilon Pi Epsilon - Honors Society',
     'school_id': 65, },
    {'_id': 63,
     'name': 'Water & Environmental Technologists (WET)',
     'school_id': 19, }
])

db.companies.drop()
db.companies.insert_many([
    {'_id': 1,
     'name': 'GM',
     'email': 'gm@gmail.com',
     'city': 'Las Vegas',
     'state': 'Nevada'},
    {'_id': 2,
     'name': 'Universe',
     'email': 'universe@gmail.com',
     'city': 'Las Vegas', 'state': 'Missouri'},
    {'_id': 3,
     'name': 'Tesla',
     'email': 'tesla@gmail.com',
     'city': 'Las Vegas', 'state': 'Florida'},
    {'_id': 4,
     'name': 'ASME National',
     'email': 'asme.national@gmail.com',
     'city': 'Las Vegas', 'state': 'California',
     'image': 'ASME'},
    {'_id': 5,
     'name': 'AIAA National',
     'email': 'aiaa.national@gmail.com',
     'city': 'Springfield', 'state': 'Florida'}
])

db.competitions.drop()
db.competitions.insert_many([
    {'_id': 1,
     'name': 'ASME Robotics',
     'description': 'Build robots with students',
     'date': datetime.datetime(1965, 8, 21),
     'website': 'www.asme.org',
     'club_ids': [1, 2, 3, 4, 5],
     'competition_host_id': 1,
     'image': 'ASME'},
    {'_id': 2,
     'name': 'AIAA Rockets',
     'description': 'Build rockets with students',
     'date': datetime.datetime(1999, 12, 31),
     'website': 'www.aiaa.org',
     'image': 'AIAA_photo_2.jpg',
     'club_ids': [3, 4, 5, 6, 7],
     'competition_host_id': 2}
])

db.competition_hosts.drop()
db.competition_hosts.insert_many([
    {'_id': 1,
     'name': 'ASME National',
     'email': 'asme.national@gmail.com',
     'city': 'Las Vegas',
     'state': 'Florida',
     'image': 'ASME'},
    {'_id': 2,
     'name': 'AIAA National',
     'email': 'aiaa.national@gmail.com',
     'city': 'Las Vegas',
     'state': 'Missouri'}
])

db.posts.drop()
db.posts.insert_many([
    {'_id': 1,
     'sender_id': 'competition 1',
     'recipient_ids': ['user 1', 'user 2', 'user 3', 'user 4', 'user 5', 'club 1', 'club 2', 'club 3', 'club 4'],
     'title': 'Registration has started',
     'text': 'The registration for the event has started. Hurry up!',
     'date': datetime.datetime(2017, 3, 3)},
    {'_id': 2,
     'sender_id': 'competition 1',
     'recipient_ids': ['user 1', 'user 2', 'user 3', 'user 4', 'user 5', 'club 1', 'club 2', 'club 3', 'club 4'],
     'title': 'Registration is closed',
     'text': 'The registration is closed. So sad, too bad!',
     'date': datetime.datetime(2017, 3, 4)},
    {'_id': 3,
     'sender_id': 'competition 1',
     'recipient_ids': ['user 1'],
     'title': 'Get ready',
     'text': 'It\'s time to get ready for the big event',
     'date': datetime.datetime(2017, 3, 1)},
    {'_id': 4,
     'sender_id': 'competition 1',
     'recipient_ids': ['club 1'],
     'title': 'Again: get ready',
     'text': 'Again: it\'s time to get ready for the big event',
     'date': datetime.datetime(2017, 3, 5)},
    {'_id': 5,
     'sender_id': 'club 8',
     'recipient_ids': ['club 1'],
     'title': 'From ASME club number 8',
     'text': 'From club 8 to club 1',
     'date': datetime.datetime(2017, 3, 13)}
])

print('== Get member by name ==')
u1 = db.users.find_one({'name': 'Sade Berney'})
print('{} - {} - {} - {}'.format(u1['name'], u1['major'], u1['city'], u1['state']))

print('== Get members by school ==')
for school in db.schools.find({}, {'name': 1}):
    #  School(school).members({'name': 1, '_id': 0})
    members = db.users.find({'school_ids': school['_id']}, {'name': 1, '_id': 0})
    if members.count():
        print('School', school['name'])
        for u in members:
            print('  ', u['name'])
    else:
        print('No users on school', school['name'])

print('== Get members by competition ==')
for competition in db.competitions.find():
    members = db.users.find({'competition_ids': competition['_id']}, {'name': 1, '_id': 0})
    if members.count():
        print('Competitions ', competition['name'])
        for u in members:
            print('  ', u['name'])
    else:
        print('No mombers on competittion', competition['name'])

print('== Get competitions by member ==')
for member in db.users.find({'competition_ids': {'$gt': []}}):
    print('Competitions of member: {}'.format(member['name']))
    for competition in db.competitions.find({'_id': {'$in': member['competition_ids']}}):
        print(' ', competition['name'])

print('== posts to user ==')
for user in db.users.find():
    print('User: {}'.format(user['name']))
    for post in User(user).to_posts:
        print('  ', post.title)
