import datetime

import pymongo

from csc.models import db, client, User, School, Competition, Post, MongoDbEntity
from csc.security import hash_password

client.drop_database('csc')

db.stuff.create_index([('username', pymongo.ASCENDING)], unique=True, sparse=True, background=True)

db.stuff.insert_many([
    # === school ===
    {'_id': 'school-1',
     '_tp': 'School',
     'name': 'Avila University',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-2',
     '_tp': 'School',
     'name': 'Baptist Bible College and Graduate School',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-3',
     '_tp': 'School',
     'name': 'Brown Mackie College St Louis',
     'city': 'Fenton',
     'state': 'Missouri'},
    {'_id': 'school-4',
     '_tp': 'School',
     'name': 'Bryan University Springfield',
     'street': '4255 S Nature Center Way',
     'city': 'Springfield',
     'state': 'Missouri',
     'zip': 65804,
     'tel': '417-862-5700',
     'image': 'BryanUniversity',
     'website': 'bryanu.edu',
     'description': 'Bryan University has been providing focused, relevant career training programs to students since '
                    '1982, when it was founded in order to meet the growing demands of students. As a career '
                    'education institution, Bryan University’s goal quickly became to teach students courses that '
                    'directly related to their field of study, providing relevant information, skills and knowledge. '
                    'Our mission is to improve the lives of our students, our team and our employers. We accomplish '
                    'our mission by providing quality education in an environment that enables our team to thrive and '
                    'our students to realize their potential, creating a positive impact within our communities.'},
    {'_id': 'school-5',
     '_tp': 'School',
     'name': 'Calvary Bible College and Theological Seminary',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-6',
     '_tp': 'School',
     'name': 'Central Bible College',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-7',
     '_tp': 'School',
     'name': 'Central Christian College of the Bible',
     'city': 'Moberly',
     'state': 'Missouri'},
    {'_id': 'school-8',
     '_tp': 'School',
     'name': 'Central Methodist University College of Liberal Arts & Sciences',
     'city': 'Fayette',
     'state': 'Missouri'},
    {'_id': 'school-9',
     '_tp': 'School',
     'name': 'Chamberlain College of Nursing Missouri',
     'city': 'St. Louis',
     'state': 'Missouri'},
    {'_id': 'school-10',
     '_tp': 'School',
     'name': 'College of the Ozarks',
     'city': 'Point Lookout',
     'state': 'Missouri'},
    {'_id': 'school-11',
     '_tp': 'School',
     'name': 'Colorado Technical University Kansas City',
     'city': 'North Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-12',
     '_tp': 'School',
     'name': 'Columbia College',
     'city': 'Columbia',
     'state': 'Missouri'},
    {'_id': 'school-13',
     '_tp': 'School',
     'name': 'Conception Seminary College',
     'city': 'Conception',
     'state': 'Missouri'},
    {'_id': 'school-14',
     '_tp': 'School',
     'name': 'Cottey College',
     'city': 'Nevada',
     'state': 'Missouri'},
    {'_id': 'school-15',
     '_tp': 'School',
     'name': 'Cox College',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-16',
     '_tp': 'School',
     'name': 'Crowder College',
     'city': 'Neosho',
     'state': 'Missouri'},
    {'_id': 'school-17',
     '_tp': 'School',
     'name': 'Culver Stockton College',
     'city': 'Canton',
     'state': 'Missouri'},
    {'_id': 'school-18',
     '_tp': 'School',
     'name': 'DeVry University Missouri',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-19',
     '_tp': 'School',
     'name': 'Drury University',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-20',
     '_tp': 'School',
     'name': 'East Central College',
     'city': 'Union',
     'state': 'Missouri'},
    {'_id': 'school-21',
     '_tp': 'School',
     'name': 'Evangel University',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-22',
     '_tp': 'School',
     'name': 'Everest College Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-23',
     '_tp': 'School',
     'name': 'Fontbonne University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-24',
     '_tp': 'School',
     'name': 'Grantham University',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-25',
     '_tp': 'School',
     'name': 'Hannibal LaGrange University',
     'city': 'Hannibal',
     'state': 'Missouri'},
    {'_id': 'school-26',
     '_tp': 'School',
     'name': 'Harris Stowe State University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-27',
     '_tp': 'School',
     'name': 'Hickey College',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-28',
     '_tp': 'School',
     'name': 'ITT Technical Institute Arnold',
     'city': 'Arnold',
     'state': 'Missouri'},
    {'_id': 'school-29',
     '_tp': 'School',
     'name': 'ITT Technical Institute Earth City',
     'city': 'Earth City',
     'state': 'Missouri'},
    {'_id': 'school-30',
     '_tp': 'School',
     'name': 'ITT Technical Institute Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-31',
     '_tp': 'School',
     'name': 'ITT Technical Institute Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-32',
     '_tp': 'School',
     'name': 'Jefferson College',
     'city': 'Hillsboro',
     'state': 'Missouri'},
    {'_id': 'school-33',
     '_tp': 'School',
     'name': 'Kansas City Art Institute',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-34',
     '_tp': 'School',
     'name': 'Kenrick Glennon Seminary',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-35',
     '_tp': 'School',
     'name': 'L\'Ecole Culinaire',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-36',
     '_tp': 'School',
     'name': 'Lincoln University',
     'city': 'Jefferson City',
     'state': 'Missouri'},
    {'_id': 'school-37',
     '_tp': 'School',
     'name': 'Lindenwood University',
     'city': 'Saint Charles',
     'state': 'Missouri'},
    {'_id': 'school-38',
     '_tp': 'School',
     'name': 'Linn State Technical College',
     'city': 'Linn',
     'state': 'Missouri'},
    {'_id': 'school-39',
     '_tp': 'School',
     'name': 'Maryville University of Saint Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-40',
     '_tp': 'School',
     'name': 'Messenger College',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 'school-41',
     '_tp': 'School',
     'name': 'Metro Business College Arnold',
     'city': 'Arnold',
     'state': 'Missouri'},
    {'_id': 'school-42',
     '_tp': 'School',
     'name': 'Metro Business College Cape Girardeau',
     'city': 'Cape Girardeau',
     'state': 'Missouri'},
    {'_id': 'school-43',
     '_tp': 'School',
     'name': 'Metro Business College Jefferson City',
     'city': 'Jefferson City',
     'state': 'Missouri'},
    {'_id': 'school-44',
     '_tp': 'School',
     'name': 'Metro Business College Rolla',
     'city': 'Rolla',
     'state': 'Missouri'},
    {'_id': 'school-45',
     '_tp': 'School',
     'name': 'Metropolitan Community College Blue River',
     'city': 'Independence',
     'state': 'Missouri'},
    {'_id': 'school-46',
     '_tp': 'School',
     'name': 'Metropolitan Community College Business & Technology',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-47',
     '_tp': 'School',
     'name': 'Metropolitan Community College Longview',
     'city': 'Lees Summit',
     'state': 'Missouri'},
    {'_id': 'school-48',
     '_tp': 'School',
     'name': 'Metropolitan Community College Maple Woods',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-49',
     '_tp': 'School',
     'name': 'Metropolitan Community College Penn Valley',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-50',
     '_tp': 'School',
     'name': 'Midwestern Baptist Theological Seminary',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-51',
     '_tp': 'School',
     'name': 'Mineral Area College',
     'city': 'Park Hills',
     'state': 'Missouri'},
    {'_id': 'school-52',
     '_tp': 'School',
     'name': 'Missouri Baptist University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-53',
     '_tp': 'School',
     'name': 'Missouri College',
     'city': 'Brentwood',
     'state': 'Missouri'},
    {'_id': 'school-54',
     '_tp': 'School',
     'name': 'Missouri Southern State University',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 'school-55',
     '_tp': 'School',
     'name': 'Missouri State University Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-56',
     '_tp': 'School',
     'name': 'Missouri State University West Plains',
     'city': 'West Plains',
     'state': 'Missouri'},
    {'_id': 'school-57',
     '_tp': 'School',
     'name': 'Missouri Tech',
     'city': 'Saint Charles',
     'state': 'Missouri'},
    {'_id': 'school-58',
     '_tp': 'School',
     'name': 'Missouri University of Science and Technology',
     'city': 'Rolla',
     'state': 'Missouri'},
    {'_id': 'school-59',
     '_tp': 'School',
     'name': 'Missouri Valley College',
     'city': 'Marshall',
     'state': 'Missouri'},
    {'_id': 'school-60',
     '_tp': 'School',
     'name': 'Missouri Western State University',
     'city': 'Saint Joseph',
     'state': 'Missouri'},
    {'_id': 'school-61',
     '_tp': 'School',
     'name': 'Moberly Area Community College',
     'city': 'Moberly',
     'state': 'Missouri'},
    {'_id': 'school-62',
     '_tp': 'School',
     'name': 'National American University Independence',
     'city': 'Independence',
     'state': 'Missouri'},
    {'_id': 'school-63',
     '_tp': 'School',
     'name': 'National American University Lee\'s Summit',
     'city': 'Lee Summit',
     'state': 'Missouri'},
    {'_id': 'school-64',
     '_tp': 'School',
     'name': 'National American University Zona Rosa',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-65',
     '_tp': 'School',
     'name': 'North Central Missouri College',
     'city': 'Trenton',
     'state': 'Missouri'},
    {'_id': 'school-66',
     '_tp': 'School',
     'name': 'Northwest Missouri State University',
     'city': 'Maryville',
     'state': 'Missouri'},
    {'_id': 'school-67',
     '_tp': 'School',
     'name': 'Ozark Christian College',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 'school-68',
     '_tp': 'School',
     'name': 'Ozarks Technical Community College',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-69',
     '_tp': 'School',
     'name': 'Park University',
     'city': 'Parkville',
     'state': 'Missouri'},
    {'_id': 'school-70',
     '_tp': 'School',
     'name': 'Pinnacle Career Institute North Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-71',
     '_tp': 'School',
     'name': 'Pinnacle Career Institute South Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-72',
     '_tp': 'School',
     'name': 'Ranken Technical College',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-73',
     '_tp': 'School',
     'name': 'Research College of Nursing',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-74',
     '_tp': 'School',
     'name': 'Rockhurst University',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-75',
     '_tp': 'School',
     'name': 'Saint Louis Christian College',
     'city': 'Florissant',
     'state': 'Missouri'},
    {'_id': 'school-76',
     '_tp': 'School',
     'name': 'Saint Louis Community College',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-77',
     '_tp': 'School',
     'name': 'Saint Louis University Main Campus',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-78',
     '_tp': 'School',
     'name': 'Sanford Brown College Fenton',
     'city': 'Fenton',
     'state': 'Missouri'},
    {'_id': 'school-79',
     '_tp': 'School',
     'name': 'Sanford Brown College Hazelwood',
     'city': 'Hazelwood',
     'state': 'Missouri'},
    {'_id': 'school-80',
     '_tp': 'School',
     'name': 'Sanford Brown College St Peters',
     'city': 'Saint Peters',
     'state': 'Missouri'},
    {'_id': 'school-81',
     '_tp': 'School',
     'name': 'Southeast Missouri Hospital College of Nursing and Health Sciences',
     'city': 'Cape Girardeau',
     'state': 'Missouri'},
    {'_id': 'school-82',
     '_tp': 'School',
     'name': 'Southeast Missouri State University',
     'city': 'Cape Girardeau',
     'state': 'Missouri'},
    {'_id': 'school-83',
     '_tp': 'School',
     'name': 'Southwest Baptist University',
     'city': 'Bolivar',
     'state': 'Missouri'},
    {'_id': 'school-84',
     '_tp': 'School',
     'name': 'St Charles Community College',
     'city': 'Cottleville',
     'state': 'Missouri'},
    {'_id': 'school-85',
     '_tp': 'School',
     'name': 'St Louis College of Health Careers Fenton',
     'city': 'Fenton',
     'state': 'Missouri'},
    {'_id': 'school-86',
     '_tp': 'School',
     'name': 'St Louis College of Health Careers St Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-87',
     '_tp': 'School',
     'name': 'St Louis College of Pharmacy',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-88',
     '_tp': 'School',
     'name': 'State Fair Community College',
     'city': 'Sedalia',
     'state': 'Missouri'},
    {'_id': 'school-89',
     '_tp': 'School',
     'name': 'Stephens College',
     'city': 'Columbia',
     'state': 'Missouri'},
    {'_id': 'school-90',
     '_tp': 'School',
     'name': 'Stevens Institute of Business & Arts',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-91',
     '_tp': 'School',
     'name': 'Texas County Technical College',
     'city': 'Houston',
     'state': 'Missouri'},
    {'_id': 'school-92',
     '_tp': 'School',
     'name': 'Three Rivers Community College',
     'city': 'Poplar Bluff',
     'state': 'Missouri'},
    {'_id': 'school-93',
     '_tp': 'School',
     'name': 'Truman State University',
     'city': 'Kirksville',
     'state': 'Missouri'},
    {'_id': 'school-94',
     '_tp': 'School',
     'name': 'University of Central Missouri',
     'city': 'Warrensburg',
     'state': 'Missouri'},
    {'_id': 'school-95',
     '_tp': 'School',
     'name': 'University of Missouri Columbia',
     'city': 'Columbia',
     'state': 'Missouri',
     'zip': 65211,
     'tel': '573-882-2121'},
    {'_id': 'school-96',
     '_tp': 'School',
     'name': 'University of Missouri Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-97',
     '_tp': 'School',
     'name': 'University of Missouri St Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-98',
     '_tp': 'School',
     'name': 'University of Phoenix Kansas City Campus',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-99',
     '_tp': 'School',
     'name': 'University of Phoenix Springfield Campus',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-100',
     '_tp': 'School',
     'name': 'University of Phoenix St Louis Campus',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-101',
     '_tp': 'School',
     'name': 'Vatterott College Berkeley',
     'city': 'Berkeley',
     'state': 'Missouri'},
    {'_id': 'school-102',
     '_tp': 'School',
     'name': 'Vatterott College Joplin',
     'city': 'Joplin',
     'state': 'Missouri'},
    {'_id': 'school-103',
     '_tp': 'School',
     'name': 'Vatterott College Kansas City',
     'city': 'Kansas City',
     'state': 'Missouri'},
    {'_id': 'school-104',
     '_tp': 'School',
     'name': 'Vatterott College Saint Joseph',
     'city': 'Saint Joseph',
     'state': 'Missouri'},
    {'_id': 'school-105',
     '_tp': 'School',
     'name': 'Vatterott College Springfield',
     'city': 'Springfield',
     'state': 'Missouri'},
    {'_id': 'school-106',
     '_tp': 'School',
     'name': 'Vatterott College St Charles',
     'city': 'St Charles',
     'state': 'Missouri'},
    {'_id': 'school-107',
     '_tp': 'School',
     'name': 'Vatterott College Sunset Hills',
     'city': 'Sunset Hills',
     'state': 'Missouri'},
    {'_id': 'school-108',
     '_tp': 'School',
     'name': 'Washington University in St Louis',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-109',
     '_tp': 'School',
     'name': 'Webster University',
     'city': 'Saint Louis',
     'state': 'Missouri'},
    {'_id': 'school-110',
     '_tp': 'School',
     'name': 'Wentworth Military Academy & Junior College',
     'city': 'Lexington',
     'state': 'Missouri'},
    {'_id': 'school-111',
     '_tp': 'School',
     'name': 'Westminster College',
     'city': 'Fulton',
     'state': 'Missouri'},
    {'_id': 'school-112',
     '_tp': 'School',
     'name': 'William Jewell College',
     'city': 'Liberty',
     'state': 'Missouri'},
    {'_id': 'school-113',
     '_tp': 'School',
     'name': 'William Woods University',
     'city': 'Fulton',
     'state': 'Missouri'},
    # === user ===
    {'_id': 'user-1',
     '_tp': 'User',
     'name': 'Stefano Menci',
     'admin': 1,
     'email': 'stefano.menci@gmail.com',
     'username': 'stefano',
     'password': hash_password('menci'),
     'photo': 'Stefano_Pic.jpg',
     'major': 'Volleyball',
     'about_me': 'I\'m Italian',
     'city': 'Olivette',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-23', 'club-3'],
     'competition_ids': ['competition-1', 'competition-2'],
     'school_ids': ['school-4', 'school-12']},
    {'_id': 'user-2',
     '_tp': 'User',
     'name': 'Brandon Torres',
     'admin': 1,
     'email': 'brandon.torres@gmail.com',
     'username': 'brandon',
     'password': hash_password('torres'),
     'photo': 'Brandon_Pic.jpg',
     'about_me': 'I am currently a student at the University of Missouri Columbia majoring in Mechanical & Aerospace Engineering. To date I have gained hands on experience in many areas of aerospace engineering including competing in an Intercollegiate Rocket Engineering Competition for AIAA (American Institute of Aeronautics and Astronautics) MU and an Unmanned Aerial Vehicle Competition for ASME (American Society of Mechanical Engineers). As of now I hold an officer position in 4 academic clubs and 1 national Vice Chair of Communications of the Student District Operating board of District 2 for ASME. At the University of Missouri I am trying not only to obtain great education but to make a difference for the future of the Engineering program. One way I have reached that goal was recently I co-founded the first MU chapter academic club SEDS. (Students for the Exploration and Development of Space). The club is designed to promote space exploration and develop a better understanding of space. Other than engineering competitions I try to reach out to the younger generation students in our local community to help promote the importance of studying STEM base subjects. Hosting rocket camps, traveling to schools to teach, and giving tours are just a small amount of the involvement that I’ve done.',
     'major': 'Mechanical Engineering',
     'city': 'University City',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-32', 'club-3'],
     'competition_ids': ['competition-1', 'competition-2'],
     'school_ids': ['school-6', 'school-10']},
    {'_id': 'user-3',
     '_tp': 'User',
     'name': 'Vance Lemoine',
     'email': 'vance.lemoine@gmail.com',
     'username': 'vance.lemoine@gmail.com',
     'password': hash_password('vance'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-13', 'club-2', 'club-3'],
     'competition_ids': ['competition-1'],
     'school_ids': ['school-64']},
    {'_id': 'user-4',
     '_tp': 'User',
     'name': 'Valencia Tripodi',
     'email': 'valencia.tripodi@gmail.com',
     'username': 'valencia.tripodi@gmail.com',
     'password': hash_password('valencia'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': ['club-31', 'club-2', 'club-3'],
     'competition_ids': ['competition-1'],
     'school_ids': ['school-110']},
    {'_id': 'user-5',
     '_tp': 'User',
     'name': 'Estelle Oram',
     'email': 'estelle.oram@gmail.com',
     'username': 'estelle.oram@gmail.com',
     'password': hash_password('estelle'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': ['club-1', 'club-2', 'club-32'],
     'competition_ids': ['competition-1'],
     'school_ids': ['school-35']},
    {'_id': 'user-6',
     '_tp': 'User',
     'name': 'Cornelius Bomberger',
     'email': 'cornelius.bomberger@gmail.com',
     'username': 'cornelius.bomberger@gmail.com',
     'password': hash_password('cornelius'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-2', 'club-23'],
     'competition_ids': ['competition-2'],
     'school_ids': ['school-11']},
    {'_id': 'user-7',
     '_tp': 'User',
     'name': 'Karyl Horvat',
     'email': 'karyl.horvat@gmail.com',
     'username': 'karyl.horvat@gmail.com',
     'password': hash_password('karyl'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': ['club-1', 'club-22', 'club-3'],
     'competition_ids': ['competition-2'],
     'school_ids': ['school-96']},
    {'_id': 'user-8',
     '_tp': 'User',
     'name': 'Delfina Wescott',
     'email': 'delfina.wescott@gmail.com',
     'username': 'delfina.wescott@gmail.com',
     'password': hash_password('delfina'),
     'major': 'Engineering',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': ['club-12', 'club-2', 'club-3'],
     'school_ids': ['school-12']},
    {'_id': 'user-9',
     '_tp': 'User',
     'name': 'Albina Hudak',
     'email': 'albina.hudak@gmail.com',
     'username': 'albina.hudak@gmail.com',
     'password': hash_password('albina'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': ['club-21', 'club-2', 'club-3'],
     'school_ids': ['school-101']},
    {'_id': 'user-10',
     '_tp': 'User',
     'name': 'Alicia Sayles',
     'email': 'alicia.sayles@gmail.com',
     'username': 'alicia.sayles@gmail.com',
     'password': hash_password('alicia'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-2', 'club-31'],
     'school_ids': ['school-49']},
    {'_id': 'user-11',
     '_tp': 'User',
     'name': 'Sade Berney',
     'email': 'sade.berney@gmail.com',
     'username': 'sade.berney@gmail.com',
     'password': hash_password('sade'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-2', 'club-13'],
     'school_ids': ['school-63']},
    {'_id': 'user-12',
     '_tp': 'User',
     'name': 'Royal Perales',
     'email': 'royal.perales@gmail.com',
     'username': 'royal.perales@gmail.com',
     'password': hash_password('royal'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-21', 'club-3'],
     'school_ids': ['school-103']},
    {'_id': 'user-13',
     '_tp': 'User',
     'name': 'Moshe Waage',
     'email': 'moshe.waage@gmail.com',
     'username': 'moshe.waage@gmail.com',
     'password': hash_password('moshe'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-12', 'club-3'],
     'school_ids': ['school-24']},
    {'_id': 'user-14',
     '_tp': 'User',
     'name': 'Devon Mcgurk',
     'email': 'devon.mcgurk@gmail.com',
     'username': 'devon.mcgurk@gmail.com',
     'password': hash_password('devon'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': ['club-11', 'club-2', 'club-3'],
     'school_ids': ['school-42', 'school-6']},
    {'_id': 'user-15',
     '_tp': 'User',
     'name': 'Kaila Blow',
     'email': 'kaila.blow@gmail.com',
     'username': 'kaila.blow@gmail.com',
     'password': hash_password('kaila'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-26', 'club-3'],
     'school_ids': ['school-3']},
    {'_id': 'user-16',
     '_tp': 'User',
     'name': 'Kermit Valladares',
     'email': 'kermit.valladares@gmail.com',
     'username': 'kermit.valladares@gmail.com',
     'password': hash_password('kermit'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-62', 'club-3'],
     'school_ids': ['school-81']},
    {'_id': 'user-17',
     '_tp': 'User',
     'name': 'Tristan Crigler',
     'email': 'tristan.crigler@gmail.com',
     'username': 'tristan.crigler@gmail.com',
     'password': hash_password('tristan'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'California',
     'club_ids': ['club-1', 'club-2', 'club-36'],
     'school_ids': ['school-19']},
    {'_id': 'user-18',
     '_tp': 'User',
     'name': 'Del Innis',
     'email': 'del.innis@gmail.com',
     'username': 'del.innis@gmail.com',
     'password': hash_password('del'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-2', 'club-63'],
     'school_ids': ['school-13']},
    {'_id': 'user-19',
     '_tp': 'User',
     'name': 'Amy Astin',
     'email': 'amy.astin@gmail.com',
     'username': 'amy.astin@gmail.com',
     'password': hash_password('amy'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': ['club-1', 'club-6', 'club-3'],
     'school_ids': ['school-76']},
    {'_id': 'user-20',
     '_tp': 'User',
     'name': 'Elois Nevarez',
     'email': 'elois.nevarez@gmail.com',
     'username': 'elois.nevarez@gmail.com',
     'password': hash_password('elois'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-61', 'club-2', 'club-3'],
     'school_ids': ['school-41']},
    {'_id': 'user-21',
     '_tp': 'User',
     'name': 'Kit Romain',
     'email': 'kit.romain@gmail.com',
     'username': 'kit.romain@gmail.com',
     'password': hash_password('kit'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': ['club-16', 'club-2', 'club-3'],
     'school_ids': ['school-77']},
    {'_id': 'user-22',
     '_tp': 'User',
     'name': 'Palma Boldt',
     'email': 'palma.boldt@gmail.com',
     'username': 'palma.boldt@gmail.com',
     'password': hash_password('palma'),
     'major': 'Engineering',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-2', 'club-35'],
     'school_ids': ['school-17']},
    {'_id': 'user-23',
     '_tp': 'User',
     'name': 'Lauralee Shewmake',
     'email': 'lauralee.shewmake@gmail.com',
     'username': 'lauralee.shewmake@gmail.com',
     'password': hash_password('lauralee'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-2', 'club-53'],
     'school_ids': ['school-11']},
    {'_id': 'user-24',
     '_tp': 'User',
     'name': 'Zaida Lisle',
     'email': 'zaida.lisle@gmail.com',
     'username': 'zaida.lisle@gmail.com',
     'password': hash_password('zaida'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-25', 'club-3'],
     'school_ids': ['school-77']},
    {'_id': 'user-25',
     '_tp': 'User',
     'name': 'Kerrie Lease',
     'email': 'kerrie.lease@gmail.com',
     'username': 'kerrie.lease@gmail.com',
     'password': hash_password('kerrie'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-52', 'club-3'],
     'school_ids': ['school-30']},
    {'_id': 'user-26',
     '_tp': 'User',
     'name': 'Vito Striplin',
     'email': 'vito.striplin@gmail.com',
     'username': 'vito.striplin@gmail.com',
     'password': hash_password('vito'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-5', 'club-3'],
     'school_ids': ['school-37']},
    {'_id': 'user-27',
     '_tp': 'User',
     'name': 'Xuan Michelson',
     'email': 'xuan.michelson@gmail.com',
     'username': 'xuan.michelson@gmail.com',
     'password': hash_password('xuan'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': ['club-15', 'club-2', 'club-3'],
     'school_ids': ['school-9']},
    {'_id': 'user-28',
     '_tp': 'User',
     'name': 'Bettyann Julien',
     'email': 'bettyann.julien@gmail.com',
     'username': 'bettyann.julien@gmail.com',
     'password': hash_password('bettyann'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': ['club-51', 'club-2', 'club-3'],
     'school_ids': ['school-106']},
    {'_id': 'user-29',
     '_tp': 'User',
     'name': 'Niki Beecher',
     'email': 'niki.beecher@gmail.com',
     'username': 'niki.beecher@gmail.com',
     'password': hash_password('niki'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'California',
     'club_ids': ['club-4', 'club-2', 'club-3'],
     'school_ids': ['school-29']},
    {'_id': 'user-30',
     '_tp': 'User',
     'name': 'Saturnina Gandhi',
     'email': 'saturnina.gandhi@gmail.com',
     'username': 'saturnina.gandhi@gmail.com',
     'password': hash_password('saturnina'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-2', 'club-34'],
     'school_ids': ['school-88']},
    {'_id': 'user-31',
     '_tp': 'User',
     'name': 'Hubert Stott',
     'email': 'hubert.stott@gmail.com',
     'username': 'hubert.stott@gmail.com',
     'password': hash_password('hubert'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'California',
     'club_ids': ['club-1', 'club-2', 'club-43'],
     'school_ids': ['school-71']},
    {'_id': 'user-32',
     '_tp': 'User',
     'name': 'Odis Pattison',
     'email': 'odis.pattison@gmail.com',
     'username': 'odis.pattison@gmail.com',
     'password': hash_password('odis'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-24', 'club-3'],
     'school_ids': ['school-69']},
    {'_id': 'user-33',
     '_tp': 'User',
     'name': 'Carmelia Brock',
     'email': 'carmelia.brock@gmail.com',
     'username': 'carmelia.brock@gmail.com',
     'password': hash_password('carmelia'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-4', 'club-3'],
     'school_ids': ['school-8']},
    {'_id': 'user-34',
     '_tp': 'User',
     'name': 'Lacey Corman',
     'email': 'lacey.corman@gmail.com',
     'username': 'lacey.corman@gmail.com',
     'password': hash_password('lacey'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': ['club-1', 'club-42', 'club-3'],
     'school_ids': ['school-106']},
    {'_id': 'user-35',
     '_tp': 'User',
     'name': 'Denyse Peavler',
     'email': 'denyse.peavler@gmail.com',
     'username': 'denyse.peavler@gmail.com',
     'password': hash_password('denyse'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': ['club-14', 'club-2', 'club-3'],
     'school_ids': ['school-56']},
    {'_id': 'user-36',
     '_tp': 'User',
     'name': 'Regine Rivenburg',
     'email': 'regine.rivenburg@gmail.com',
     'username': 'regine.rivenburg@gmail.com',
     'password': hash_password('regine'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': ['club-41', 'club-2', 'club-3'],
     'school_ids': ['school-48']},
    {'_id': 'user-37',
     '_tp': 'User',
     'name': 'Arleen Samons',
     'email': 'arleen.samons@gmail.com',
     'username': 'arleen.samons@gmail.com',
     'password': hash_password('arleen'),
     'major': 'Engineering',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': ['club-11', 'club-2', 'club-3'],
     'school_ids': ['school-101']},
    {'_id': 'user-38',
     '_tp': 'User',
     'name': 'Mindy Stearman',
     'email': 'mindy.stearman@gmail.com',
     'username': 'mindy.stearman@gmail.com',
     'password': hash_password('mindy'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': ['club-1', 'club-2', 'club-33'],
     'school_ids': ['school-30']},
    {'_id': 'user-39',
     '_tp': 'User',
     'name': 'Henrietta Wolken',
     'email': 'henrietta.wolken@gmail.com',
     'username': 'henrietta.wolken@gmail.com',
     'password': hash_password('henrietta'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-32', 'club-3'],
     'school_ids': ['school-97']},
    {'_id': 'user-40',
     '_tp': 'User',
     'name': 'Jenae Hamm',
     'email': 'jenae.hamm@gmail.com',
     'username': 'jenae.hamm@gmail.com',
     'password': hash_password('jenae'),
     'major': 'Business',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': ['club-1', 'club-23', 'club-3'],
     'school_ids': ['school-77']},
    {'_id': 'user-41',
     '_tp': 'User',
     'name': 'Pete Pendergraft',
     'email': 'pete.pendergraft@gmail.com',
     'username': 'pete.pendergraft@gmail.com',
     'password': hash_password('pete'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': ['club-13', 'club-2', 'club-3'],
     'school_ids': ['school-42']},
    {'_id': 'user-42',
     '_tp': 'User',
     'name': 'Tad Anderton',
     'email': 'tad.anderton@gmail.com',
     'username': 'tad.anderton@gmail.com',
     'password': hash_password('tad'),
     'major': 'Business',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-31', 'club-2', 'club-3'],
     'school_ids': ['school-48']},
    {'_id': 'user-43',
     '_tp': 'User',
     'name': 'Vince Sunderman',
     'email': 'vince.sunderman@gmail.com',
     'username': 'vince.sunderman@gmail.com',
     'password': hash_password('vince'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-2', 'club-32'],
     'school_ids': ['school-41']},
    {'_id': 'user-44',
     '_tp': 'User',
     'name': 'Virgie Hipple',
     'email': 'virgie.hipple@gmail.com',
     'username': 'virgie.hipple@gmail.com',
     'password': hash_password('virgie'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'California',
     'club_ids': ['club-1', 'club-2', 'club-23'],
     'school_ids': ['school-97']},
    {'_id': 'user-45',
     '_tp': 'User',
     'name': 'Ashley Gitlin',
     'email': 'ashley.gitlin@gmail.com',
     'username': 'ashley.gitlin@gmail.com',
     'password': hash_password('ashley'),
     'major': 'Communication',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-22', 'club-3'],
     'school_ids': ['school-113']},
    {'_id': 'user-46',
     '_tp': 'User',
     'name': 'Julia Denner',
     'email': 'julia.denner@gmail.com',
     'username': 'julia.denner@gmail.com',
     'password': hash_password('julia'),
     'major': 'Communication',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-12', 'club-2', 'club-3'],
     'school_ids': ['school-59']},
    {'_id': 'user-47',
     '_tp': 'User',
     'name': 'Elana Cuffee',
     'email': 'elana.cuffee@gmail.com',
     'username': 'elana.cuffee@gmail.com',
     'password': hash_password('elana'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-2', 'club-23'],
     'school_ids': ['school-81']},
    {'_id': 'user-48',
     '_tp': 'User',
     'name': 'Rozanne Garden',
     'email': 'rozanne.garden@gmail.com',
     'username': 'rozanne.garden@gmail.com',
     'password': hash_password('rozanne'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'California',
     'club_ids': ['club-1', 'club-22', 'club-3'],
     'school_ids': ['school-45']},
    {'_id': 'user-49',
     '_tp': 'User',
     'name': 'Salley Quiroz',
     'email': 'salley.quiroz@gmail.com',
     'username': 'salley.quiroz@gmail.com',
     'password': hash_password('salley'),
     'major': 'Business',
     'city': 'Pensacola',
     'state': 'Missouri',
     'club_ids': ['club-21', 'club-2', 'club-3'],
     'school_ids': ['school-84']},
    {'_id': 'user-50',
     '_tp': 'User',
     'name': 'Ozell Costas',
     'email': 'ozell.costas@gmail.com',
     'username': 'ozell.costas@gmail.com',
     'password': hash_password('ozell'),
     'major': 'Communication',
     'city': 'Las Vegas',
     'state': 'Missouri',
     'club_ids': ['club-11', 'club-2', 'club-3'],
     'school_ids': ['school-3']},
    {'_id': 'user-51',
     '_tp': 'User',
     'name': 'Vivienne Hardee',
     'email': 'vivienne.hardee@gmail.com',
     'username': 'vivienne.hardee@gmail.com',
     'password': hash_password('vivienne'),
     'major': 'Engineering',
     'city': 'Springfield',
     'state': 'Missouri',
     'club_ids': ['club-1', 'club-2', 'club-13'],
     'school_ids': ['school-68']},
    {'_id': 'user-52',
     '_tp': 'User',
     'name': 'Shawnee Driskill',
     'email': 'shawnee.driskill@gmail.com',
     'username': 'shawnee.driskill@gmail.com',
     'password': hash_password('shawnee'),
     'major': 'Engineering',
     'city': 'Las Vegas',
     'state': 'Florida',
     'club_ids': ['club-1', 'club-12', 'club-3'],
     'school_ids': ['school-72']},
    # === club ===
    {'_id': 'club-1',
     '_tp': 'Club',
     'name': 'Alpha Epsilon-Honors Society',
     'school_id': 'school-7',
     'officers': {'user-2': 'President',
                  'user-3': 'Vicepresident',
                  'user-4': 'Treasurer',
                  'user-5': 'Secretary'}},
    {'_id': 'club-2',
     '_tp': 'Club',
     'name': 'Alpha Omega Epsilon Sorority',
     'school_id': 'school-29'},
    {'_id': 'club-3',
     '_tp': 'Club',
     'name': 'Alpha Pi Mu - Honors Society',
     'school_id': 'school-4',
     'officers': {'user-1': 'President',
                  'user-2': 'Vicepresident',
                  'user-3': 'Treasurer',
                  'user-6': 'Secretary'},
     'image': 'Alpha Pi Mu - Honors Society'},
    {'_id': 'club-4',
     '_tp': 'Club',
     'name': 'American Institute of Aeronautics & Astronautics (AIAA)',
     'school_id': 'school-12'},
    {'_id': 'club-5',
     '_tp': 'Club',
     'name': 'American Institute of Chemical Engineers',
     'school_id': 'school-47'},
    {'_id': 'club-6',
     '_tp': 'Club',
     'name': 'American Society of Civil Engineers (ASCE)',
     'school_id': 'school-4'},
    {'_id': 'club-7',
     '_tp': 'Club',
     'name': 'American Society of Mechanical Engineers',
     'school_id': 'school-35'},
    {'_id': 'club-8',
     '_tp': 'Club',
     'name': 'ASME Student Professional Development Conference',
     'school_id': 'school-4',
     'image': 'ASME'},
    {'_id': 'club-9',
     '_tp': 'Club',
     'name': 'Association for Computing Machinery',
     'school_id': 'school-75',
     'officers': {'user-12': 'President',
                  'user-13': 'Vicepresident',
                  'user-14': 'Treasurer',
                  'user-15': 'Secretary'}},
    {'_id': 'club-10',
     '_tp': 'Club',
     'name': 'Bioengineering',
     'school_id': 'school-57'},
    {'_id': 'club-11',
     '_tp': 'Club',
     'name': 'Biomedical Competitive Advancement Team (BioCATs)',
     'school_id': 'school-34'},
    {'_id': 'club-12',
     '_tp': 'Club',
     'name': 'Biomedical Engineering Society',
     'school_id': 'school-109'},
    {'_id': 'club-13',
     '_tp': 'Club',
     'name': 'Chemical',
     'school_id': 'school-22'},
    {'_id': 'club-14',
     '_tp': 'Club',
     'name': 'Chi Epsilon - Honors Society',
     'school_id': 'school-93'},
    {'_id': 'club-15',
     '_tp': 'Club',
     'name': 'Civil & Environmental',
     'school_id': 'school-17'},
    {'_id': 'club-16',
     '_tp': 'Club',
     'name': 'Computer Science',
     'school_id': 'school-89'},
    {'_id': 'club-17',
     '_tp': 'Club',
     'name': 'Computer Science Graduate Student Council',
     'school_id': 'school-71'},
    {'_id': 'club-18',
     '_tp': 'Club',
     'name': 'Concrete Bowling Team',
     'school_id': 'school-30'},
    {'_id': 'club-19',
     '_tp': 'Club',
     'name': 'Concrete Canoe Team',
     'school_id': 'school-27'},
    {'_id': 'club-20',
     '_tp': 'Club',
     'name': 'Contact Faculty Advisers',
     'school_id': 'school-19'},
    {'_id': 'club-21',
     '_tp': 'Club',
     'name': 'ECE Graduate Student Association',
     'school_id': 'school-36'},
    {'_id': 'club-22',
     '_tp': 'Club',
     'name': 'Electrical & Computer',
     'school_id': 'school-43'},
    {'_id': 'club-23',
     '_tp': 'Club',
     'name': 'Engineer’s Club / St. Pat’s Board',
     'school_id': 'school-5'},
    {'_id': 'club-24',
     '_tp': 'Club',
     'name': 'Engineering Ambassadors',
     'school_id': 'school-104'},
    {'_id': 'club-25',
     '_tp': 'Club',
     'name': 'Engineering Student Council',
     'school_id': 'school-22'},
    {'_id': 'club-26',
     '_tp': 'Club',
     'name': 'Engineering World Health',
     'school_id': 'school-5'},
    {'_id': 'club-27',
     '_tp': 'Club',
     'name': 'Engineers Without Borders',
     'school_id': 'school-4'},
    {'_id': 'club-28',
     '_tp': 'Club',
     'name': 'Eta Kappa Nu - Honors Society',
     'school_id': 'school-99'},
    {'_id': 'club-29',
     '_tp': 'Club',
     'name': 'E-Week (Engineers’ Week)',
     'school_id': 'school-45'},
    {'_id': 'club-30',
     '_tp': 'Club',
     'name': 'Formula Car Racing Team (FSAE)',
     'school_id': 'school-27'},
    {'_id': 'club-31',
     '_tp': 'Club',
     'name': 'Graduates’ Club of Biological Engineering (GCBE)',
     'school_id': 'school-44'},
    {'_id': 'club-32',
     '_tp': 'Club',
     'name': 'IEEE CIS Society',
     'school_id': 'school-56'},
    {'_id': 'club-33',
     '_tp': 'Club',
     'name': 'Industrial & Manufacturing Systems',
     'school_id': 'school-75'},
    {'_id': 'club-34',
     '_tp': 'Club',
     'name': 'Institute of Biological Engineering',
     'school_id': 'school-15'},
    {'_id': 'club-35',
     '_tp': 'Club',
     'name': 'Institute of Electrical and Electronics Engineering (IEEE)',
     'school_id': 'school-91'},
    {'_id': 'club-36',
     '_tp': 'Club',
     'name': 'Institute of Industrial Engineers',
     'school_id': 'school-46'},
    {'_id': 'club-37',
     '_tp': 'Club',
     'name': 'Mechanical & Aerospace',
     'school_id': 'school-61'},
    {'_id': 'club-38',
     '_tp': 'Club',
     'name': 'Mechanical Contractors Association of America',
     'school_id': 'school-112'},
    {'_id': 'club-39',
     '_tp': 'Club',
     'name': 'Mizzou 3D Printing Club',
     'school_id': 'school-111'},
    {'_id': 'club-40',
     '_tp': 'Club',
     'name': 'Mizzou ASHRAE',
     'school_id': 'school-51'},
    {'_id': 'club-41',
     '_tp': 'Club',
     'name': 'Mizzou Baja Racing (BSAE)',
     'school_id': 'school-81'},
    {'_id': 'club-42',
     '_tp': 'Club',
     'name': 'Mizzou Eco-Racing',
     'school_id': 'school-94'},
    {'_id': 'club-43',
     '_tp': 'Club',
     'name': 'Mizzou Electric Car Club',
     'school_id': 'school-97'},
    {'_id': 'club-44',
     '_tp': 'Club',
     'name': 'Mizzou Student Chapter',
     'school_id': 'school-50'},
    {'_id': 'club-45',
     '_tp': 'Club',
     'name': 'Mizzou Unmanned Systems Team (MUST)',
     'school_id': 'school-26'},
    {'_id': 'club-46',
     '_tp': 'Club',
     'name': 'Mizzou Women Mentoring Women',
     'school_id': 'school-111'},
    {'_id': 'club-47',
     '_tp': 'Club',
     'name': 'National Language Processing Journal Club',
     'school_id': 'school-83'},
    {'_id': 'club-48',
     '_tp': 'Club',
     'name': 'National Society of Black Engineers',
     'school_id': 'school-111'},
    {'_id': 'club-49',
     '_tp': 'Club',
     'name': 'Omega Chi Epsilon - Honors Society',
     'school_id': 'school-81'},
    {'_id': 'club-50',
     '_tp': 'Club',
     'name': 'Pi Tau Sigma - Honors Society',
     'school_id': 'school-49'},
    {'_id': 'club-51',
     '_tp': 'Club',
     'name': 'Sigma Alpha Sorority',
     'school_id': 'school-13'},
    {'_id': 'club-52',
     '_tp': 'Club',
     'name': 'Sigma Phi Delta',
     'school_id': 'school-62'},
    {'_id': 'club-53',
     '_tp': 'Club',
     'name': 'Society of Hispanic Professional Engineers',
     'school_id': 'school-6'},
    {'_id': 'club-54',
     '_tp': 'Club',
     'name': 'Society of Manufacturing Engineers',
     'school_id': 'school-71'},
    {'_id': 'club-55',
     '_tp': 'Club',
     'name': 'Society of Manufacturing Engineers',
     'school_id': 'school-53'},
    {'_id': 'club-56',
     '_tp': 'Club',
     'name': 'Society of Women Engineers',
     'school_id': 'school-32'},
    {'_id': 'club-57',
     '_tp': 'Club',
     'name': 'Steel Bridge Team',
     'school_id': 'school-62'},
    {'_id': 'club-58',
     '_tp': 'Club',
     'name': 'Students for the Exploration and Development of Space (SEDS)',
     'school_id': 'school-83', },
    {'_id': 'club-59',
     '_tp': 'Club',
     'name': 'Tau Beta Pi - Engineering Honors Society',
     'school_id': 'school-26', },
    {'_id': 'club-60',
     '_tp': 'Club',
     'name': 'Timber Bridge Team',
     'school_id': 'school-103', },
    {'_id': 'club-61',
     '_tp': 'Club',
     'name': 'Torq’N Tigers Tractor Pulling TeamGeneral Interest',
     'school_id': 'school-92', },
    {'_id': 'club-62',
     '_tp': 'Club',
     'name': 'Upsilon Pi Epsilon - Honors Society',
     'school_id': 'school-65', },
    {'_id': 'club-63',
     '_tp': 'Club',
     'name': 'Water & Environmental Technologists (WET)',
     'school_id': 'school-19', },
    # === company ===
    {'_id': 'company-1',
     '_tp': 'Company',
     'name': 'GM',
     'email': 'gm@gmail.com',
     'username': 'gm@gmail.com',
     'city': 'Las Vegas',
     'state': 'Nevada'},
    {'_id': 'company-2',
     '_tp': 'Company',
     'name': 'Universe',
     'email': 'universe@gmail.com',
     'username': 'universe@gmail.com',
     'city': 'Las Vegas', 'state': 'Missouri'},
    {'_id': 'company-3',
     '_tp': 'Company',
     'name': 'Tesla',
     'email': 'tesla@gmail.com',
     'username': 'tesla@gmail.com',
     'city': 'Las Vegas', 'state': 'Florida'},
    # === competition ===
    {'_id': 'competition-1',
     '_tp': 'Competition',
     'name': 'ASME Robotics',
     'description': 'Build robots with students',
     'date': datetime.datetime(1965, 8, 21),
     'website': 'www.asme.org',
     'club_ids': ['club-1', 'club-2', 'club-3', 'club-4', 'club-5'],
     'competition_host_id': 1,
     'image': 'ASME'},
    {'_id': 'competition-2',
     '_tp': 'Competition',
     'name': 'AIAA Rockets',
     'description': 'Build rockets with students',
     'date': datetime.datetime(1999, 12, 31),
     'website': 'www.aiaa.org',
     'image': 'AIAA_photo_2.jpg',
     'club_ids': ['club-3', 'club-4', 'club-5', 'club-6', 'club-7'],
     'competition_host_id': 2},
    # === competition_hosts ===
    {'_id': 'competition_host-1',
     '_tp': 'CompetitionHost',
     'name': 'ASME National',
     'email': 'asme.national@gmail.com',
     'username': 'asme.national@gmail.com',
     'city': 'Las Vegas',
     'state': 'Florida',
     'image': 'ASME'},
    {'_id': 'competition_host-2',
     '_tp': 'CompetitionHost',
     'name': 'AIAA National',
     'email': 'aiaa.national@gmail.com',
     'username': 'aiaa.national@gmail.com',
     'city': 'Las Vegas',
     'state': 'Missouri'},
    # === post ===
    {'_id': 'post-1',
     '_tp': 'Post',
     'sender_id': 'competition-1',
     'recipient_ids': ['user-1', 'user-2', 'user-3', 'user-4', 'user-5', 'club-1', 'club-2', 'club-3', 'club-4'],
     'title': 'Registration has started',
     'text': 'The registration for the event has started. Hurry up!',
     'date': datetime.datetime(2017, 3, 3)},
    {'_id': 'post-2',
     '_tp': 'Post',
     'sender_id': 'competition-1',
     'recipient_ids': ['user-1', 'user-2', 'user-3', 'user-4', 'user-5', 'club-1', 'club-2', 'club-3', 'club-4'],
     'title': 'Registration is closed',
     'text': 'The registration is closed. Too bad, so sad!',
     'date': datetime.datetime(2017, 3, 4)},
    {'_id': 'post-3',
     '_tp': 'Post',
     'sender_id': 'competition-1',
     'recipient_ids': ['user-1'],
     'title': 'Get ready',
     'text': 'It\'s time to get ready for the big event',
     'date': datetime.datetime(2017, 3, 1)},
    {'_id': 'post-4',
     '_tp': 'Post',
     'sender_id': 'competition-1',
     'recipient_ids': ['club-1'],
     'title': 'Again: get ready',
     'text': 'Again: it\'s time to get ready for the big event',
     'date': datetime.datetime(2017, 3, 5)},
    {'_id': 'post-5',
     '_tp': 'Post',
     'sender_id': 'club-8',
     'recipient_ids': ['club-1'],
     'title': 'From ASME club number 8',
     'text': 'From club 8 to club 1',
     'date': datetime.datetime(2017, 3, 13)},
])

print('== Get member by name ==')
u1 = User.find_one({'name': 'Sade Berney'})
print('{} - {} - {} - {}'.format(u1['name'], u1['major'], u1['city'], u1['state']))

print('== Get clubs by school ==')
for school in School.find():
    print('School: {}'.format(school.name))
    found = False
    for club in school.clubs:
        print('  ', club.name)
        found = True
    if not found:
        print('   no clubs')

print('== Get members by school ==')
for school in School.find({}, ['_id', 'name']):
    print('School', school.name)
    found = False
    for u in school.students:
        print('  ', u['name'])
        found = True
    if not found:
        print('   no students')

print('== Get members by competition ==')
for competition in Competition.find():
    members = competition.members()
    print('Competitions ', competition.name)
    found = False
    for u in members:
        print('  ', u.name)
        found = True
    if not found:
        print('No mombers on competittion', competition.name)

print('== Get competitions by member ==')
for member in User.find({'competition_ids': {'$gt': []}}):
    print('Competitions of member: {}'.format(member.name))
    for competition in member.competitions:
        print(' ', competition.name)

print('== Posts to user ==')
for user in User.find():
    print('User: {}'.format(user.name))
    for post in user.to_posts:
        print('  ', post.title)

print('== Posts recipients ==')
for post in Post.find():
    print('Post: {}'.format(post.title))
    print('  Sender: ', post.sender.name)
    print('  Recipients: ', [r.name for r in post.recipients])
